### ISSUE TITLE
Make profiles actually be a python object.

### ISSUE THREAD

**Issue by chibill** [awkman/pywifi#12]
Just opening this to say what i am working on for a PR.

And for comments on it.

it will allow for implementing more of the following.

https://msdn.microsoft.com/en-us/library/windows/desktop/ms707348(v=vs.85).aspx

**Comment by chibill** [comment]
This could also be expanded to to linux implementation as you can make windows only fields be None.

**Comment by awkman** [comment]
Because I want to remove the dependency on dbus in Linux env, I already rewrite Linux part to directly communicate with wpa_supplicant via socket. So, now please ignore Linux part until I commit the code.

What fields are you adding now? I could help to check the source code of wpa_supplicant(Linux) to confirm is there any similar fields.

**Comment by chibill** [comment]
Well firstly I was going to pull all the fields out of the .xml we receive from the call to the api. This way we can easily support any of the encryption and auth types. (They list all of them in the area I linked.)

But some of the fields seem sort of use-less so I will start listing them. 

Firstly add encryption as a field instead of looking at auth type to guess it. (In the add_netwrok_profile call)

Also add sharedKey Which represents a dict with keyType ,protected and also keyMaterial.

**Comment by chibill** [comment]
Any thought on it?

**Comment by awkman** [comment]
Is it okay for you to send the PR first? Generally, I agree with your point and I think we can continue this discussion based on your modification. I will help you to modify linux part.

**Comment by chibill** [comment]
Okay. Will do
